version: '3'
services:
  my-app:
    init: true
    image: ghcr.io/afomiat/my-app:3.0
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      # We construct the connection string using variables
      - MONGO_URL=${DB_USERNAME}:${DB_PASSWORD}@mongo:27017
      - MONGO_DB_USERNAME=${DB_USERNAME}
      - MONGO_DB_PWD=${DB_PASSWORD}

  mongo:
    init: true
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      # This sets the actual credentials inside the Database
      - MONGO_INITDB_ROOT_USERNAME=${DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}

  mongo-express:
    init: true
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${DB_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${DB_PASSWORD}
      - ME_CONFIG_MONGODB_SERVER=mongo

volumes:
  mongo-data: